apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-rule-infra-baseline
  namespace: infra-baseline-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: vendor
      operator: In
      values:
      - "Openshift"