apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-infra-baseline
policyDefaults:
  namespace: infra-baseline-policies
  remediationAction: enforce
  severity: medium
policies:
  - name: oauth-policy
    manifests:
      - path: oauth
  - name: gitops-operator-policy
    manifests:
      - path: gitops