apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-argo-dev-policies
  namespace: app-argo-dev-policies
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - app-argo-dev-policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications-argo/dev
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: app-argo-dev-policies
  name: app-argo-dev-policies-subscription
  namespace: app-argo-dev-policies
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - PlacementRule
  channel: ggithubcom-frangalloreply-poc-acm-2022-ns/ggithubcom-frangalloreply-poc-acm-2022
  placement:
    placementRef:
      kind: PlacementRule
      name: app-argo-dev-policies-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: app-argo-dev-policies
  name: app-argo-dev-policies-placement
  namespace: app-argo-dev-policies
spec:
  clusterReplicas: 1   # Availability choice, maximum number of clusters to provision at once
  clusterSelector:
    matchLabels:
      'environment': 'dev'
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"