apiVersion: v1
kind: Namespace
metadata:
  name: app-argo-dev-policies
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-argo-dev
  namespace: app-argo-dev-policies
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - app-argo-dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: app-argo-dev-subscription-1
  namespace: app-argo-dev-policies
  annotations:
    apps.open-cluster-management.io/cluster-admin: 'true'
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications-argo/dev
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: app-argo-dev
    app.kubernetes.io/part-of: app-argo-dev
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: ggithubcom-frangalloreply-poc-acm-2022-ns/ggithubcom-frangalloreply-poc-acm-2022
  placement:
    placementRef:
      name: app-argo-dev-placement-1
      kind: PlacementRule
posthooks: {}
prehooks: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: app-argo-dev-placement-1
  namespace: app-argo-dev-policies
  annotations:
  labels:
    app: app-argo-dev
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'