apiVersion: v1
kind: Namespace
metadata:
  name: infra-baseline-policies
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: infra-baseline-policies
  namespace: infra-baseline-policies
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - infra-baseline-policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: infra-baseline
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: infra-baseline-policies
  name: infra-baseline-policies-subscription
  namespace: infra-baseline-policies
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - PlacementRule
  channel: ggithubcom-frangalloreply-poc-acm-2022-ns/ggithubcom-frangalloreply-poc-acm-2022
  placement:
    placementRef:
      kind: PlacementRule
      name: infra-baseline-policies-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: infra-baseline-policies
  name: infra-baseline-policies-placement
  namespace: infra-baseline-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"