apiVersion: v1
kind: Namespace
metadata:
  name: app1-d
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pacman-sample
  namespace: app1-d
spec:
  template: 
    metadata:
      name: 'pacman'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/jnpacker/application-samples.git
        targetRevision: main
        path: pacman
      destination:
        namespace: pacman
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true