apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: generator-ocp-oauth
#placementBindingDefaults:
#  name: placement-binding-ocp-oauth
policyDefaults:
  namespace: acm-policies
  complianceType: mustonlyhave
  remediationAction: enforce
  severity: high
policies:
  - name: policy-ocp-oauth
    manifests:
      - path: default
    placement:
      clusterSelectors:
        cluster-network: default
