apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-rule-argo-app-dev
  namespace: app-argo-dev-policies
spec:
  clusterSelector:
    matchExpressions:
    - key: environment
      operator: In
      values:
      - "dev"