apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-argo-app-dev-aks
placementBindingDefaults:
  name: placement-rule-argo-app-dev-aks
policyDefaults:
  namespace: app-argo-dev-aks-policies
  remediationAction: enforce
  severity: medium
  complianceType: mustonlyhave
  placement:
    name: placement-rule-argo-app-dev-aks
    clusterSelectors:
      environment: development
      vendor: AKS
policies:
  - name: app1-d
    manifests:
      - path: app1/aks